#ifndef CCGE_CONSTS_DATADEFINE_H_
#define CCGE_CONSTS_DATADEFINE_H_

/**
 * table名称
 */
#define CCGE_TABLE_SKILLS "skills"
#define CCGE_TABLE_SKILL_ACTINS "skill_actins"
#define CCGE_TABLE_UNITS "units"
#define CCGE_TABLE_BUFFS "buffs"

/**
 * data名称
 */

#define CCGE_DATA_PLAYROLE "PlayRole"
#define CCGE_DATA_BATTLE_TYPE "battleType"
#define CCGE_DATA_BATTLE_OPPID "oppId"
#define CCGE_DATA_PROPERTY_CONFIG_ENTITY "entity"
#define CCGE_DATA_PROPERTY_CONFIG_BATTLE "battle"

//battle cell
#define CCGE_BATTLE_CELL_COL "col"
#define CCGE_BATTLE_CELL_ROW "row"
#define CCGE_BATTLE_CELL_SIDE "side"
#define CCGE_BATTLE_CELL_SCALE "scale"

//unit
#define CCGE_UNIT_ID "id"
#define CCGE_UNIT_NAME "name"
#define CCGE_UNIT_DESCRIPTION "description"
#define CCGE_UNIT_LEVEL "level"
#define CCGE_UNIT_BASE_HEALTH "base_health"
#define CCGE_UNIT_BASE_MANA "base_mana"
#define CCGE_UNIT_BASE_DEFENCE "base_defence"
#define CCGE_UNIT_BASE_DAMAGE "base_damage"
#define CCGE_UNIT_BASE_AGILITY "base_agility"
#define CCGE_UNIT_BASE_ATTACK_SPEED "base_attack_speed"
#define CCGE_UNIT_GROW_HEALTH "grow_health"
#define CCGE_UNIT_GROW_MANA "grow_mana"
#define CCGE_UNIT_GROW_DEFENCE "grow_defence"
#define CCGE_UNIT_GROW_DAMAGE "grow_damage"
#define CCGE_UNIT_GROW_AGILITY "grow_agility"
#define CCGE_UNIT_GROW_TYPE "grow_type"

#define CCGE_UNIT_MAX_HEALTH "max_health"
#define CCGE_UNIT_MAX_MANA "max_mana"

#define CCGE_UNIT_HEALTH "health"
#define CCGE_UNIT_MANA "mana"
#define CCGE_UNIT_DEFENCE "defence"
#define CCGE_UNIT_DAMAGE "damage"
#define CCGE_UNIT_AGILITY "agility"
#define CCGE_UNIT_ATTACK_SPEED "attack_speed"
#define CCGE_UNIT_ATTACK_TYPE "attack_type"
#define CCGE_UNIT_WALK_SPEED "walk_speed"

#define CCGE_UNIT_ICON "icon"

#define CCGE_UNIT_PUPPET_ID "puppet_id"

//skill
#define CCGE_SKILL_ID "id"
#define CCGE_SKILL_NAME "name"
#define CCGE_SKILL_ATTACK_TYPE "attack_type"
#define CCGE_SKILL_DAMAGE_TYPE "damage_type"
#define CCGE_SKILL_TARGET_TYPE "target_type"
#define CCGE_SKILL_TARGET_CAMP "target_camp"
#define CCGE_SKILL_MAX_RANGE "max_range"
#define CCGE_SKILL_MIN_RANGE "min_range"
#define CCGE_SKILL_INIT_CD "init_cd"
#define CCGE_SKILL_GLOBAL_CD "global_cd"
#define CCGE_SKILL_CD "cd"
#define CCGE_SKILL_MANUAL "manual"
#define CCGE_SKILL_COST_MP "cost_mp"
#define CCGE_SKILL_ACTIVE_TYPE "active_type"
#define CCGE_SKILL_KNOCK_UP "knock_up"
#define CCGE_SKILL_KNOCK_BACK "knock_back"
#define CCGE_SKILL_MOVE_FORWARD "move_forward"
#define CCGE_SKILL_AFFECTED_CAMP "affected_camp"
#define CCGE_SKILL_AFFECT_FIELD "affect_field"
#define CCGE_SKILL_GAIN_MP "gain_mp"
#define CCGE_SKILL_LEVEL "level"
#define CCGE_SKILL_BUFF_ID "buff_id"
#define CCGE_SKILL_LIFE_DRAIN_RATIO "life_drain_ratio"
#define CCGE_SKILL_CRIT_RATIO "crit_ratio"
#define CCGE_SKILL_OUTSIDE_SCREEN "outside_screen"
#define CCGE_SKILL_BASIC_NUM "basic_num"
#define CCGE_SKILL_PASSIVE_ATTR "passive_attr"
#define CCGE_SKILL_PLUS_ATTR "plus_attr"
#define CCGE_SKILL_PLUS_RATIO "plus_ratio"
#define CCGE_SKILL_CHAIN_GAP "chain_gap"
#define CCGE_SKILL_CHAIN_JUMPS "chain_jumps"
#define CCGE_SKILL_TILE_GRAVITY "tile_gravity"
#define CCGE_SKILL_TILE_XY_SPEED "tile_xy_speed"
#define CCGE_SKILL_TILE_Z_SPEED "tile_z_speed"
#define CCGE_SKILL_TILE_OTT_HEIGHT "tile_ott_height"
#define CCGE_SKILL_TILE_PIERCING "tile_piercing"
#define CCGE_SKILL_TILE_DISTANCE "tile_distance"
#define CCGE_SKILL_AIM_TARGET "aim_target"
#define CCGE_SKILL_ACTION_ID "action_id"
#define CCGE_SKILL_ACTIONS "actions"
#define CCGE_SKILL_X_SHIFT "x_shift"
#define CCGE_SKILL_LAUNCH_EFFECT "launch_effect"
#define CCGE_SKILL_IMPACT_EFFECT "impact_effect"
#define CCGE_SKILL_IMPACT_ZORDER "impact_zorder"
#define CCGE_SKILL_POINT_EFFECT "point_effect"
#define CCGE_SKILL_POINT_ZORDER "point_zorder"
#define CCGE_SKILL_AOE_SHAPE "aoe_shape"
#define CCGE_SKILL_SHAPE_ARG1 "shape_arg1"
#define CCGE_SKILL_SHAPE_ARG2 "shape_arg2"
#define CCGE_SKILL_SCRIPT_ARG1 "script_arg1"
#define CCGE_SKILL_SCRIPT_ARG2 "script_arg2"
#define CCGE_SKILL_SCRIPT_ARG3 "script_arg3"
#define CCGE_SKILL_SCRIPT_ARG4 "script_arg4"
#define CCGE_SKILL_SCRIPT_ARG5 "script_arg5"
#define CCGE_SKILL_SCRIPT_ARG6 "script_arg6"
#define CCGE_SKILL_DESCRIPTION "description"

//monster
#define CCGE_MONSTER_ID "id"
#define CCGE_MONSTER_UNIT_ID "unit_id"
#define CCGE_MONSTER_LEVEL "level"
#define CCGE_MONSTER_SKILL1 "skill1"
#define CCGE_MONSTER_SKILL2 "skill2"
#define CCGE_MONSTER_SKILL3 "skill3"
#define CCGE_MONSTER_SKILL4 "skill4"
#define CCGE_MONSTER_EQUIP_BODY "equip_body"
#define CCGE_MONSTER_EQUIP_WEAPON "equip_weapon"
#define CCGE_MONSTER_EQUIP_DECORATION "equip_decoration"
#define CCGE_MONSTER_SCALE "scale"

//player
#define CCGE_PLAYER_ID "id"
#define CCGE_PLAYER_USER_ID "user_id"
#define CCGE_PLAYER_UNIT_ID "unit_id"
#define CCGE_PLAYER_LEVEL "level"
#define CCGE_PLAYER_SKILL1 "skill1"
#define CCGE_PLAYER_SKILL2 "skill2"
#define CCGE_PLAYER_SKILL3 "skill3"
#define CCGE_PLAYER_SKILL4 "skill4"
#define CCGE_PLAYER_EQUIP_BODY "equip_body"
#define CCGE_PLAYER_EQUIP_WEAPON "equip_weapon"
#define CCGE_PLAYER_EQUIP_DECORATION "equip_decoration"
#define CCGE_PLAYER_SCALE "scale"

#endif /* defined(CCGE_CONSTS_DATADEFINE_H_) */
